version: '3.9'
services:
  backend:
    build: .
    command: uvicorn src.asgi:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

volumes:
  mongo_data:
